---
title: "PRIVIA PROJECT"
authors: "David Cevallos-Salas, José Estrada-Jiménez, Danny S. Guamán"
output:
  html_document:
    df_print: paged
---

```{r warning=FALSE, include=FALSE}
library(sur)
library(ggplot2)
library(ggpubr)
library(readxl)
library(viridis)
library(dplyr)
library(tidyr)
library(readr)
library(colorspace)
```

```{r warning=FALSE, include=FALSE}
categories <- read_csv("E:/Doctorado/PrivacyAssessmentFrontend/Statistics/categories_hallucinations_test.csv", show_col_types = FALSE)

n <- n_distinct(categories$category)

if (n <= 24) {
palette <- c(
  "#FF0000", # rojo
  "#0000FF", # azul
  "#00FF00", # verde
  "#8B4513", # café/marrón
  "#000000", # negro
  "#FFA500", # naranja
  "#800080", # morado
  "#00FFFF", # cian
  "#FFC0CB", # rosa
  "#808080", # gris
  "#008080", # teal
  "#FF1493", # deep pink
  "#4B0082", # índigo
  "#40E0D0", # turquesa
  "#FF4500", # naranja rojizo
  "#6A5ACD", # slate blue
  "#2E8B57", # verde mar
  "#00CED1", # dark turquoise
  "#D2691E", # chocolate
  "#BA55D3", # medium orchid
  "#4682B4", # steel blue
  "#9ACD32", # amarillo verdoso (evita amarillo puro)
  "#CD5C5C", # indian red
  "#20B2AA"  # light sea green
)
  palette <- palette[1:n]
} else {
  palette <- viridis(n, alpha= 1, begin = 0.1, end = 0.9, direction = -1, option="viridis")  
}

data <- read_csv("E:/Doctorado/PrivacyAssessmentFrontend/Statistics/logprobs_hallucinations_test.csv", show_col_types = FALSE)

ct <- seq(from = 0, to = 1, by = 0.05)

```


### Hallucinations

```{r warning=FALSE, echo=FALSE}
df <- data.frame()

for (umbral in ct) {
  data_filtered <- data %>%
    filter(exp(logprob) >= umbral & logprob > -10)
  
  count <- data_filtered %>%
    group_by(category) %>%
    summarise(subclause_count = n_distinct(goal), .groups = "drop")
  
  partial <- categories %>%
    select(category) %>%
    left_join(count, by = "category") %>%
    mutate(subclause_count = ifelse(is.na(subclause_count), 0, subclause_count),
           ct = umbral)
  
  df <- bind_rows(df, partial)
  df$category <- factor(df$category, levels = categories$category)
}

picturesubclauses <- ggplot(df, aes(x = ct, y = subclause_count, color = category)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                     labels = scales::number_format(accuracy = 0.01)) +
  scale_y_continuous(breaks = seq(0, max(df$subclause_count), by = 1),
                     labels = scales::number_format(accuracy = 1)) +
  scale_color_manual(values = palette)+
  labs(
    x = "Confidence threshold",
    y = "Hallucinations",
    color = "Standard / Privacy Legal Framework"
  ) +
  theme_light()

picturesubclauses
```
```

