---
title: "PRIVIA PROJECT"
authors: "David Cevallos-Salas, José Estrada-Jiménez, Danny S. Guamán"
output:
  html_document:
    df_print: paged
---

```{r warning=FALSE, include=FALSE}
library(sur)
library(ggplot2)
library(ggpubr)
library(readxl)
library(viridis)
library(dplyr)
library(tidyr)
library(readr)
```

```{r warning=FALSE, include=FALSE}
categories <- read_csv("E:/Doctorado/PrivacyAssessmentFrontend/Statistics/categories.csv", show_col_types = FALSE)

n <- n_distinct(categories$category)
palette <- viridis(n, alpha= 1, begin = 0.1, end = 0.9, direction = -1, option="viridis")

data <- read_csv("E:/Doctorado/PrivacyAssessmentFrontend/Statistics/logprobs.csv", show_col_types = FALSE)

ct <- seq(from = 0, to = 1, by = 0.05)

```

### Number of principles met by confidence threshold

```{r warning=FALSE,echo=FALSE}
df <- data.frame()

for (umbral in ct) {
  data_filtrada <- data %>%
    filter(exp(logprob) >= umbral)
  
  count <- data_filtrada %>%
    group_by(category) %>%
    summarise(principle_count = n_distinct(principle), .groups = "drop")
  
  partial <- categories %>%
    select(category) %>%
    left_join(count, by = "category") %>%
    mutate(principle_count = ifelse(is.na(principle_count), 0, principle_count),
           ct = umbral)
  
  df <- bind_rows(df, partial)
  df$category <- factor(df$category, levels = categories$category)
}

picturePrincipes <- ggplot(df, aes(x = ct, y = principle_count, color = category)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                     labels = scales::number_format(accuracy = 0.01)) +
  scale_y_continuous(breaks = seq(0, max(df$principle_count), by = 1),
                     labels = scales::number_format(accuracy = 1)) +
  scale_color_manual(values = palette) +
  labs(
    x = "Confidence threshold",
    y = "Number of principles met",
    color = "Normative / Law"
  ) +
  theme_light()

picturePrincipes
```

### Number of goals met by confidence threshold

```{r warning=FALSE, echo=FALSE}
df <- data.frame()

for (umbral in ct) {
  data_filtrada <- data %>%
    filter(exp(logprob) >= umbral)
  
  count <- data_filtrada %>%
    group_by(category) %>%
    summarise(goal_count = n_distinct(goal), .groups = "drop")
  
  partial <- categories %>%
    select(category) %>%
    left_join(count, by = "category") %>%
    mutate(goal_count = ifelse(is.na(goal_count), 0, goal_count),
           ct = umbral)
  
  df <- bind_rows(df, partial)
  df$category <- factor(df$category, levels = categories$category)
}

pictureGoals <- ggplot(df, aes(x = ct, y = goal_count, color = category)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                     labels = scales::number_format(accuracy = 0.01)) +
  scale_y_continuous(breaks = seq(0, max(df$goal_count), by = 1),
                     labels = scales::number_format(accuracy = 1)) +
  scale_color_manual(values = palette)+
  labs(
    x = "Confidence threshold",
    y = "Number of goals met",
    color = "Normative / Law"
  ) +
  theme_light()

pictureGoals
```


