---
title: "A GPT-Based Assessment of Privacy Legal Frameworks with ISO/IEC 27701:2025: A Latin American Case Study"
authors: "David Cevallos-Salas, José Estrada-Jiménez, Danny S. Guamán"
output:
  html_document:
    df_print: paged
---

```{r}
library(ggplot2)
```


```{r}
thresholds = c(0.0,0.05,0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65,0.7,0.75,0.8,0.85,0.9,0.95,1.0)
kappas = c(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.6461538461538462,0.03157894736842093)

df <- data.frame(
  thresholds = thresholds,
  kappas = kappas
)
```

```{r}
y_top <- ceiling(1 * 10) / 10   # rounds up to next 0.1

picture <- ggplot(df, aes(x = thresholds, y = kappas)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(
    breaks = seq(0, 1, by = 0.1),
    labels = scales::number_format(accuracy = 0.01)
  ) +
  scale_y_continuous(
    limits = c(0, y_top),
    breaks = seq(0, y_top, by = 0.1),
    labels = scales::number_format(accuracy = 0.01)
  ) +
  labs(
    x = "Confidence threshold",
    #y = expression("Cohen's Kappa (" * kappa * ") coefficient")
    y = expression("Cohen's kappa coefficient")
  ) +
  theme_light()

picture
```

